version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://db:5432/attendance_system
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: attendance_system
      POSTGRES_USER: ridhotamma
      POSTGRES_PASSWORD: 
      POSTGRES_HOST_AUTH_METHOD: trust
